######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 20 12:35:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml
QMAKE_CXXFLAGS += -g3

# Input
HEADERS += file.h sftags-wnd.h main.h tagsbox.h
FORMS += sftags.ui
SOURCES += file.cc sftags-wnd.cc main.cc tagsbox.cc
